### ISSUE TITLE
Questions on Data Sets

### ISSUE THREAD

**Issue by wanglinwangyinuo** [sergivalverde/sub-cortical_segmentation#4]
I use the IBSR dataset as input, but there are problems.:
  --> loading weights from  /home/wanglin/sub-cortical_segmentation-master/nets/IBSR/IBSR.pkl
         --> registering priors for scan T1.nii
Traceback (most recent call last):
  File "train_model.py", line 77, in <module>
    t = test_scan(net, t1, options)
  File "/home/wanglin/sub-cortical_segmentation-master/cnn_cort/base.py", line 421, in test_scan
    for batch_axial, batch_cor, batch_sag, atlas, centers in load_patch_batch(test_scan, options):
  File "/home/wanglin/sub-cortical_segmentation-master/cnn_cort/base.py", line 364, in load_patch_batch
    t = register_masks(scan_name)
  File "/home/wanglin/sub-cortical_segmentation-master/cnn_cort/base.py", line 538, in register_masks
    s_atlas[:,:,:,st] = r_tmp_atlas.get_data().astype(np.float32)
ValueError: could not broadcast input array from shape (256,256,128) into shape (256,256,128,15)

And the IBSR. pkl folder is empty, I don't know why.

**Comment by wanglinwangyinuo** [comment]
Can you send us the data set of MICCAI 2012? I can't find it online. Thank you very much.
